name: Deploy WordPress to GoDaddy via rsync
on:
  workflow_dispatch:
    inputs:
      deployment_dest:
        description: 'Target server directory, leave blank for root directory'
        required: false
        default: '/wp-content/themes/rainsplat/'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Synchronize Files with GoDaddy WordPress Hosting Server
        uses: godaddy-wordpress/gd-wordpress-deployer@v1
        with:
          remote_host: "d8k.99f.myftpupload.com"
          ssh_user: "git_deployer_9710b1a64e_440743"
          ssh_private_key: ${{secrets.PRIVATE_KEY}}
          deployment_dest: ${{ github.event.inputs.deployment_dest }}
          exclude_list: "wp-config.php,.htaccess,wp-content/plugins/,wp-content/uploads/"
